#Worksheet-1

 1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
empty_array=np.empty((2,2))
print(empty_array)

[[4.77225523e-310 0.00000000e+000]
 [6.82051887e-310 4.77280161e-310]]


2. Initialize an all one array with size 4X2

In [ ]:
all_one_array=np.ones((4,2))
print(all_one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
def first_array(fill_value):
  return np.full((3,2),fill_value)
first_array(6)

array([[6, 6],
       [6, 6],
       [6, 6]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
def zeros_array(shape):
  return np.zeros_like(shape)
make_zero = np.array([[3,4,5],[4,5,6]])
zeros_array(make_zero)


array([[0, 0, 0],
       [0, 0, 0]])

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
def ones_array(shape):
  return np.ones_like(shape)
make_zero = np.array([[3,4,5],[4,5,6]])
ones_array(make_zero)

array([[1, 1, 1],
       [1, 1, 1]])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1,2,3,4]
to_numpy = np.array(new_list)
print(to_numpy)

[1 2 3 4]


#Problem-2

 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
#Problem:2
random_values = np.arange(10,49)
print(random_values)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}

In [ ]:
three_matrix = np.arange(0,9).reshape(3,3)
print(three_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


 3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}

In [ ]:
random_array = np.random.random(30)
random_mean = np.mean(random_array)
print(random_array)
print("The mean of Random Array is:",random_mean)

[0.46449479 0.09780134 0.73451437 0.37092809 0.96517208 0.06189026
 0.46195204 0.63521909 0.08972017 0.97217511 0.42209298 0.58105344
 0.48914648 0.06389438 0.03711336 0.11790346 0.17438583 0.86597187
 0.61092774 0.29571328 0.03807512 0.7003052  0.55691875 0.34335429
 0.56666868 0.29748715 0.21079133 0.55521307 0.40978252 0.80668751]
The mean of Random Array is: 0.4332451260661106


5. Create a 10X10 array with random values and find the minimum and maximum values

In [ ]:
ten_by_ten = np.random.rand(10,10)
print("The 10X10 matrix is :", ten_by_ten)
min_value = ten_by_ten.min()
max_value = ten_by_ten.max()
print("The minimum value is :", min_value)
print("The maximum value is :", max_value)
#

The 10X10 matrix is : [[0.18091001 0.01700119 0.34365174 0.25862911 0.11623631 0.75491581
  0.58154174 0.70509941 0.72783851 0.91579223]
 [0.91629458 0.33274702 0.84594746 0.3785004  0.27234859 0.90895094
  0.28321397 0.47068071 0.99915135 0.42198118]
 [0.26928302 0.37458851 0.12323218 0.30806194 0.01611721 0.81460365
  0.03623036 0.23780324 0.49318399 0.11325049]
 [0.23410354 0.7358642  0.6545273  0.24789986 0.95833023 0.53592964
  0.48704558 0.52697672 0.80158968 0.60211276]
 [0.12065853 0.25240213 0.62712361 0.64747404 0.78569815 0.9333416
  0.82538197 0.26992662 0.28513936 0.61431047]
 [0.69368044 0.13542667 0.9650751  0.12304323 0.09424419 0.78116881
  0.46367618 0.55692048 0.23361527 0.07589258]
 [0.54590732 0.79246924 0.7403556  0.9237862  0.64380963 0.47245484
  0.83939516 0.44494964 0.09876107 0.22011285]
 [0.22682145 0.63552209 0.93986014 0.09996853 0.35446464 0.22397222
  0.78233615 0.16427211 0.24646421 0.63782486]
 [0.84740573 0.69219803 0.64306352 0.90714476 0.32479306 0.

 6. Create a zero array of size 10 and replace 5th element with 1

In [ ]:
zero_aray = np.zeros(10)
zero_aray[4] = 1
print(zero_aray)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0]

In [ ]:
arr = [1,2,0,0,4,4]
reversed_array = np.flip(arr)
print(reversed_array)

[4 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside

In [ ]:
arr = np.ones((6,6))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern

In [ ]:
checker_board = np.zeros((8,8))
checker_board[1::2,::2] = 1
checker_board[::2,1::2] = 1
print(checker_board)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#Problem-3

In [ ]:
from re import sub
# Problem 3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
# Addition of Arrays
add_arrays = x+y
print(f"The sum of the given arrays is:\n{add_arrays}")
#Subtraction of Arrays
sub_arrays = x-y
print(f"The difference of the given arrays is:\n{sub_arrays}")
#Multiplication of Arrays
multiarray = x*y
print(f"The product of the given arrays is:\n{multiarray}")
#Square of arrays
squara_array = np.square(x)
print(f"The square of the given arrays is:\n{squara_array}")
#Dot Product of v,w
dot_product1 = np.dot(v,w)
print(f"The dot product of the given arrays is:\n{dot_product1}")
# Dot Product of x,v
dot_product = np.dot(x,v)
print(f"The dot product of the given arrays is:\n{dot_product}")
#Dot product of x,y
dot_product_x_y = np.dot(x,y)
print(f"The dot product of the given arrays is:\n{dot_product_x_y}")

#Concatenate x and y along row
concat_row = np.concatenate((x,y),axis=0)
print(f"The concatenated row of the given arrays is:\n{concat_row}")

#Concatenate v and w along column
concat_col=np.concatenate((v,w))
print(f"The concatenated column of the given arrays is:\n{concat_col}")

concat_x_v = np.concatenate((x,v))
print(f"The concatenated column of the given arrays is:\n{concat_x_v}")
## Error


The sum of the given arrays is:
[[ 6  8]
 [10 13]]
The difference of the given arrays is:
[[-4 -4]
 [-4 -3]]
The product of the given arrays is:
[[ 5 12]
 [21 40]]
The square of the given arrays is:
[[ 1  4]
 [ 9 25]]
The dot product of the given arrays is:
219
The dot product of the given arrays is:
[29 77]
The dot product of the given arrays is:
[[19 22]
 [50 58]]
The concatenated row of the given arrays is:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
The concatenated column of the given arrays is:
[ 9 10 11 12]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

#Problem4

In [ ]:
import numpy as np

# Define the matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I
inverse_A = np.linalg.inv(A)
AA_inv = np.dot(A, inverse_A)
identity_matrix = np.eye(A.shape[0])  # Generate a 2x2 identity matrix
print(f"A:\n{A}")
print(f"Inverse of A (A⁻¹):\n{inverse_A}")
print(f"A * A⁻¹:\n{AA_inv}")
print(f"Identity matrix (I):\n{identity_matrix}")
print(f"A * A⁻¹ equals I: {np.allclose(AA_inv, identity_matrix)}\n")

# 2. Prove AB = BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print(f"A * B:\n{AB}")
print(f"B * A:\n{BA}")
print(f"AB equals BA: {np.allclose(AB, BA)}\n")

# 3. Prove (AB)ᵀ = Bᵀ * Aᵀ
AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print(f"(AB)ᵀ:\n{AB_T}")
print(f"Bᵀ * Aᵀ:\n{BT_AT}")
print(f"(AB)ᵀ equals Bᵀ * Aᵀ: {np.allclose(AB_T, BT_AT)}\n")

# Define matrix A and B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve using inverse method
A_inv = np.linalg.inv(A_eq)
X = np.dot(A_inv, B_eq)
print(f"The solution X (using inverse method) is:\n{X}\n")

# Solve using np.linalg.solve (preferred method for numerical stability)
X_solve = np.linalg.solve(A_eq, B_eq)
print(f"The solution X (using np.linalg.solve) is:\n{X_solve}")


The inverse of A is:
[[-2.    1.  ]
 [ 1.75 -0.75]]
The dot product of A is:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
The identity matrix is:
[[1. 0.]
 [0. 1.]]
